# Generated by Django 5.2.3 on 2025-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_document_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(default="file", max_length=200),
        ),
    ]
