# Generated by Django 5.2.3 on 2025-07-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_document_original_filename"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="created_date",
            new_name="created_at",
        ),
    ]
