# Generated by Django 5.2.3 on 2025-07-07 16:38

import django.db.models.deletion
import nanoid.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_created_date_course_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=nanoid.generate,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("choice_1", models.CharField(default="", max_length=250)),
                ("choice_2", models.CharField(default="", max_length=250)),
                ("choice_3", models.CharField(default="", max_length=250)),
                ("choice_4", models.CharField(default="", max_length=250)),
                ("correct_ans", models.IntegerField()),
                ("explanation", models.CharField(max_length=500)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.document"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShortQuestion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=nanoid.generate,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("correct_ans", models.CharField(max_length=500)),
                ("explanation", models.CharField(max_length=500)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.document"
                    ),
                ),
            ],
        ),
    ]
