# Generated by Django 5.2.3 on 2025-07-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_multiplechoicequestion_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multiplechoicequestion",
            name="explanation",
        ),
        migrations.RemoveField(
            model_name="shortquestion",
            name="explanation",
        ),
    ]
