# Generated by Django 5.2.3 on 2025-07-09 14:34

import django.db.models.deletion
import nanoid.generate
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_shortquestion_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=nanoid.generate,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.document"
                    ),
                ),
                (
                    "multiple_choice_questions",
                    models.ManyToManyField(
                        blank=True, to="core.multiplechoicequestion"
                    ),
                ),
                (
                    "short_questions",
                    models.ManyToManyField(blank=True, to="core.shortquestion"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
