# Generated by Django 5.2.3 on 2025-07-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-07-01 18:33:50"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-07-01 18:33:50"),
            preserve_default=False,
        ),
    ]
