# Generated by Django 5.2.3 on 2025-07-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chat_created_at_message_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="document",
        ),
    ]
