# Generated by Django 5.2.3 on 2025-07-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_chat_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="course",
        ),
    ]
