# Generated by Django 5.2.3 on 2025-07-14 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_chat_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="last_message_time",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(1, 1, 1, 0, 0)
            ),
            preserve_default=False,
        ),
    ]
